class occupy_options:
    def __init__(self,
        input_map: str = None,
        resolution: float = -1,
        amplify: float = -1,
        attenuate: float = -1,
        sigmoid: float = -1,
        pivot: float = -1,
        tau: float = -1,
        kernel_size: int = -1,
        tile_size: int = -1,
        lowpass_input: float = -1,
        lowpass_output: float = -1,
        exclude_solvent : bool = False,
        max_box: int = -1,
        hedge_confidence: int = -1,
        solvent_def: str = None,
        scale_limit: float = -1,
        hist_match: int = -1,
        output_map: str = None,
        plot : bool = False,
        save_all_maps : bool = False,
        chimerax : bool= True,
        chimerax_silent : bool = False,
        show_chimerax : bool = False,
        min_vis_scale: float = -1,
        s0 : bool = False,
        lp_scale = bool(None),
        emdb_id : str = None,
        verbose : bool = False,
        help_all : bool = False,
        version : bool = False
):
        self.input_map = input_map
        self.resolution = resolution
        self.amplify = amplify
        self.attenuate = attenuate
        self.sigmoid = sigmoid
        self.pivot = pivot
        self.tau = tau
        self.kernel_size = kernel_size
        self.tile_size = tile_size
        self.lowpass_input = lowpass_input
        self.lowpass_output = lowpass_output
        self.exclude_solvent = exclude_solvent
        self.max_box = max_box
        self.hedge_confidence = hedge_confidence
        self.solvent_def = solvent_def
        self.scale_limit = scale_limit
        self.hist_match = hist_match
        self.output_map = output_map
        self.plot = plot
        self.save_all_maps = save_all_maps
        self.chimerax = chimerax
        self.chimerax_silent = chimerax_silent
        self.show_chimerax = show_chimerax
        self.min_vis_scale = min_vis_scale
        self.s0 = s0
        self.lp_scale = lp_scale
        self.emdb_id = emdb_id
        self.verbose = verbose
        self.help_all = help_all
        self.version = version